---
title: "Untitled"
output: html_document
date: "2024-10-29"
---

```{r}
#load packages
library(here)
library(sf)
library(readr)
library(dplyr)
library(tidyr)
library(janitor)
library(tmap)

```

```{r}
# read data
index <- read_csv(here("data", "hdr-data.csv"))
country <- st_read(here("data","World_Countries.geojson"))


Datatypelist <- index %>% 
  summarise_all(class) %>%
  pivot_longer(everything(), 
               names_to = "All_variables", 
               values_to = "Variable_class")
Datatypelist

# select and filter
index2 <- index %>%
  clean_names(.) %>%
  select(country, year, value) %>%
  filter(year == 2019 | year == 2010) %>%
  group_by(country) %>%
  summarise(
    index_2010 = value[year == 2010],   
    index_2019 = value[year == 2019],   
    index_diff = index_2010 - index_2019 
  )%>%
  na.omit()

#! id code instead of name
# join to the spatial data
joined_data <- country %>% 
  clean_names(.) %>%
  left_join(.,
            index2, by = "country")  
# output  sf object: columns of your difference, and then  country name or some ID value


```

