---
title: "使用 Moran's I、LISA及其相关函数分析空间自相关"
output: html_document
date: "2024-11-19"
---
## 数据下载
```{r}
library(here)
library(janitor)
library(sf)
library(tidyverse)
#read the ward data in
LondonWards <- st_read(here::here("data",
                                  "statistical-gis-boundaries-london", 
                                  "ESRI", 
                                  "London_Ward.shp"))

LondonWardsMerged <- st_read(here::here("data",
                                        "statistical-gis-boundaries-london",
                                        "ESRI",
                                        "London_Ward_CityMerged.shp"))%>%
  st_transform(.,27700)

WardData <- read_csv("https://data.london.gov.uk/download/ward-profiles-and-atlas/772d2d64-e8c6-46cb-86f9-e52b4c7851bc/ward-profiles-excel-version.csv",
                    locale = locale(encoding = "latin1"),
                     na = c("NA", "n/a")) %>% 
  clean_names()

LondonWardsMerged <- LondonWardsMerged %>% 
  left_join(WardData, 
            by = c("GSS_CODE" = "new_code"))%>%
  dplyr::distinct(GSS_CODE, .keep_all = T)%>%
  dplyr::select(GSS_CODE, ward_name, average_gcse_capped_point_scores_2014)
```
绘制数据以检查是否合理
```{r}
library(tmap)

BluePlaques <- st_read("https://s3.eu-west-2.amazonaws.com/openplaques/open-plaques-london-2018-04-08.geojson") %>%
    st_transform(.,27700)

tmap_mode("plot")
tm_shape(LondonWardsMerged) +
  tm_polygons(col = NA, alpha = 0.5) +
tm_shape(BluePlaques) +
  tm_dots(col = "blue")
```
## 数据清理
```{r}
# 去掉伦敦城外的蓝色牌匾
summary(BluePlaques)

BluePlaquesSub <- BluePlaques[LondonWardsMerged,]

tm_shape(LondonWardsMerged) +
  tm_polygons(col = NA, alpha = 0.5) +
tm_shape(BluePlaquesSub) +
  tm_dots(col = "blue")
```
## 数据处理
使用空间自相关
```{r}
# 使用st_intersects()而不是st_join(),左连接会使其多一行，如果病房为空
example<-st_intersects(LondonWardsMerged, BluePlaquesSub)

example
# 检查ID=Kingston upon Thames - Coombe Hill的多边形有几块牌匾
check_example <- LondonWardsMerged%>%
  st_join(BluePlaquesSub)%>%
  filter(ward_name=="Kingston upon Thames - Coombe Hill")

# 取每个多边形的每个列表的长度并将其添加为新列
library(sf)
points_sf_joined <- LondonWardsMerged%>%
  mutate(n = lengths(st_intersects(., BluePlaquesSub)))%>%
  janitor::clean_names()%>%
  #calculate area
  mutate(area=st_area(.))%>%
  #then density of the points per ward
  mutate(density=n/area)%>%
  #select density and some other variables 
  dplyr::select(density, ward_name, gss_code, n, average_gcse_capped_point_scores_2014)

# 绘制分级统计地图
points_sf_joined<- points_sf_joined %>%                    
  group_by(gss_code) %>%         
  summarise(density = first(density),
          wardname= first(ward_name),
          plaquecount= first(n))

tm_shape(points_sf_joined) +
    tm_polygons("density",
        style="jenks",
        palette="PuOr",
        midpoint=NA,
        popup.vars=c("wardname", "density"),
        title="Blue Plaque Density")
```
## 权重矩阵
1.定义一个Wij空间权重矩阵
```{r}
# install.packages("spdep")
library(spdep)

#First calculate the centroids of all Wards in London

coordsW <- points_sf_joined%>%
  st_centroid()%>%
  st_geometry()
  
plot(coordsW,axes=TRUE)
```
2.生成一个空间权重矩阵
```{r}
#firstly, create a neighbours list
LWard_nb <- points_sf_joined %>%
  poly2nb(., queen=T)

summary(LWard_nb)

#then, plot them
plot(LWard_nb, st_geometry(coordsW), col="red")
#add a map underneath
plot(points_sf_joined$geometry, add=T)
```
3.矩阵样式
```{r}
#create a spatial weights matrix from these weights
Lward.lw <- LWard_nb %>%
  nb2mat(., style="B")

sum(Lward.lw)

# 行标准化
sum(Lward.lw[1,])
```
## 自相关

定义完矩阵，可以进行统计数据的计算
1. Moran's I 需要空间权重列表类型对象而不是矩阵
是否有聚集值（接近1）或分散值（接近-1）
```{r}
Lward.lw <- LWard_nb %>%
  nb2listw(., style="C")

I_LWard_Global_Density <- points_sf_joined %>%
  pull(density) %>%
  as.vector()%>%
  moran.test(., Lward.lw)

I_LWard_Global_Density

```
2.Geary’s C 
是否聚类
```{r}
C_LWard_Global_Density <- 
  points_sf_joined %>%
  pull(density) %>%
  as.vector()%>%
  geary.test(., Lward.lw)

C_LWard_Global_Density
```
3.Getis Ord

